name: LiDAR
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_0
  - accelerate=0.22.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.11=hd590300_1
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - aom=3.9.0=hac33072_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.20=h5f1c8d9_0
  - aws-c-cal=0.6.12=h2ba76a8_0
  - aws-c-common=0.9.17=h4ab18f5_0
  - aws-c-compression=0.2.18=h36a0aea_4
  - aws-c-event-stream=0.4.2=h161de36_10
  - aws-c-http=0.8.1=h63f54a0_13
  - aws-c-io=0.14.8=h96d4d28_0
  - aws-c-mqtt=0.10.4=hcc7299c_2
  - aws-c-s3=0.5.8=h10bd90f_3
  - aws-c-sdkutils=0.1.16=h36a0aea_0
  - aws-checksums=0.1.18=h36a0aea_4
  - aws-crt-cpp=0.26.8=h02fd9b4_10
  - aws-sdk-cpp=1.11.267=h51dfee4_8
  - black=23.7.0=py310hff52083_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cryptography=42.0.7=py310hb1bd9d3_0
  - cuda-cudart=12.1.105=hd3aeb46_0
  - cuda-cudart_linux-64=12.1.105=h59595ed_0
  - cuda-cupti=12.1.105=h59595ed_0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=hd3aeb46_0
  - cuda-nvtx=12.1.105=h59595ed_0
  - cuda-opencl=12.1.105=h59595ed_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.1=h1d6eff3_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - datasets=2.16.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.7=pyhd8ed1ab_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - einops=0.6.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=7.0.0=gpl_h9c209ab_101
  - filelock=3.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2023.10.0=pyhca7485f_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=he1b5a44_1004
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - glog=0.7.0=hed5481d_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.5=py310hc3586ac_0
  - gnutls=3.7.9=hb077bed_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.62.2=py310h1b8f574_0
  - gst-plugins-base=1.24.3=h9ad1361_0
  - gstreamer=1.24.3=haf2f30d_0
  - harfbuzz=8.4.0=h3d44ed6_0
  - huggingface_hub=0.23.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - imageio=2.34.0=pyh4b66e23_0
  - imageio-ffmpeg=0.4.9=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - kornia=0.7.0=pyhd8ed1ab_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libarrow=16.0.0=hefa796f_1_cpu
  - libarrow-acero=16.0.0=hac33072_1_cpu
  - libarrow-dataset=16.0.0=hac33072_1_cpu
  - libarrow-substrait=16.0.0=h7e0c224_1_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.5=default_h5d6823c_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.6.1.9=hd3aeb46_0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.2.106=hd3aeb46_0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.120=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h77fa898_7
  - libgcrypt=1.10.3=hd590300_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgoogle-cloud=2.23.0=h9be4e54_1
  - libgoogle-cloud-storage=2.23.0=hc7a4891_1
  - libgpg-error=1.49=h4f305b6_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.10.0=default_h2fb2949_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.5=hb77312f_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=hd3aeb46_0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.4=h7f98852_1
  - libopenvino=2024.1.0=h2da1b83_5
  - libopenvino-auto-batch-plugin=2024.1.0=hb045406_5
  - libopenvino-auto-plugin=2024.1.0=hb045406_5
  - libopenvino-hetero-plugin=2024.1.0=h5c03a75_5
  - libopenvino-intel-cpu-plugin=2024.1.0=h2da1b83_5
  - libopenvino-intel-gpu-plugin=2024.1.0=h2da1b83_5
  - libopenvino-intel-npu-plugin=2024.1.0=he02047a_5
  - libopenvino-ir-frontend=2024.1.0=h5c03a75_5
  - libopenvino-onnx-frontend=2024.1.0=h07e8aee_5
  - libopenvino-paddle-frontend=2024.1.0=h07e8aee_5
  - libopenvino-pytorch-frontend=2024.1.0=he02047a_5
  - libopenvino-tensorflow-frontend=2024.1.0=h39126c6_5
  - libopenvino-tensorflow-lite-frontend=2024.1.0=he02047a_5
  - libopus=1.3.1=h7f98852_1
  - libparquet=16.0.0=h6a7eafb_1_cpu
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libsystemd0=255=h3516f8a_1
  - libtasn1=4.19.0=h166bdaf_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.0=h59595ed_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.6=h232c23b_2
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.40.1=py310h1b8f574_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib=3.7.1=py310hff52083_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py310h2372a71_0
  - multiprocess=0.70.15=py310h2372a71_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.100=hca3bf56_0
  - numba=0.57.0=py310h0f6aa51_2
  - numpy=1.24.4=py310ha4c1d20_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - ocl-icd=2.3.2=hd590300_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.0=hd590300_0
  - orc=2.0.0=h17fec99_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py310hcc13569_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.3.0=py310hf73ecf8_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.1=pyhd8ed1ab_0
  - protobuf=4.25.3=py310ha8c1f0e_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pyarrow=16.0.0=py310h17c5347_0
  - pyarrow-core=16.0.0=py310h6f79a3a_0_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.6.3=pyhd8ed1ab_0
  - pydantic-core=2.16.3=py310hcb5633a_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py310h2372a71_0
  - python_abi=3.10=4_cp310
  - pytorch=2.1.0=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - qt-main=5.15.8=hc9dc06e_21
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rich=13.5.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.4.13=he19d79f_0
  - scipy=1.11.1=py310ha4c1d20_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - simple-parsing=0.1.5=pyhd8ed1ab_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hdb0a2a9_1
  - svt-av1=2.0.0=h59595ed_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.12.0=h00ab1b0_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h75e40e8_1
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchtriton=2.1.0=py310
  - torchvision=0.16.0=py310_cu121
  - tornado=6.4=py310h2372a71_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - beartype==0.18.5
      - causal-conv1d==1.0.0
      - ema-pytorch==0.4.8
      - ftfy==6.2.0
      - joblib==1.4.2
      - mamba-ssm==1.0.1
      - ninja==1.11.1.1
      - regex==2024.5.10
      - safetensors==0.4.3
      - tokenizers==0.19.1
      - transformers==4.40.2
      - wcwidth==0.2.13
prefix: /root/anaconda3/envs/LiDAR
